### PR TITLE
Refactor build

### PR DESCRIPTION
**Pull request by jxstxn1**
This is the first step of refactoring our build logic

**Merging to main will break the run command**

### CODE REVIEW

**Comment by robiness** [comment]
`docker build image`
Does only output
`✓ [dockerize] Built Docker Image 🎉 (2.1s)`
Should we have 2 additional lines for building flutter and scripts? I got confused first that only the image got build 🤔

**Comment by jxstxn1** [comment]
> `docker build image`
> 
> Does only output
> 
> `✓ [dockerize] Built Docker Image 🎉 (2.1s)`
> 
> Should we have 2 additional lines for building flutter and scripts? I got confused first that only the image got build 🤔

It's updated during the build in the CLI to reduce terminal output

**Review by robiness — APPROVED** [review]
👌

**Review by Dev-dfm — APPROVED** [review]
🌮

**Pull request merged**
